name: install wordpress 
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main 

jobs:
  install_httpd:
    runs-on: linux

    steps:
      - name: setup ssh 
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.4.1
        with: 
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-host: ${{ env.PHOST }}
          
      - name: install httpd
        run: | 
           ssh ec2-user@3.6.92.170 'sudo yum -y update && sudo yum -y install httpd php unzip && sudo systemctl enable --now httpd'

  deploy_code:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo 
        uses: actions/checkout@v4.1.7

      - name: setup ssh 
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.4.1
        with: 
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-host: 3.6.92.170
          
      - name: copy artifact 
        run : |
          scp index.html ec2-user@3.6.92.170://home/ec2-user/
          ssh ec2-user@3.6.92.170 'sudo cp /home/ec2-user/index.html /var/www/html/'
            

